"""
Seed Data for Minkart Online Shopping System
"""

SAMPLE_PRODUCTS = [
    {
        "name": "Apple MacBook Air M2",
        "category": "Electronics",
        "brand": "Apple",
        "price": 105471,
        "original_price": 115068,
        "discount_percentage": 8,
        "stock": 15,
        "rating": 4.9,
        "review_count": 240,
        "description": "Supercharged by M2 chip. Thin, light, and powerful with 13.6-inch Liquid Retina display and up to 18 hours of battery life.",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-001",
        "featured": 1,
    },
    {
        "name": "Dell XPS 15 Laptop",
        "category": "Electronics",
        "brand": "Dell",
        "price": 139061,
        "original_price": 163053,
        "discount_percentage": 15,
        "stock": 10,
        "rating": 4.7,
        "review_count": 115,
        "description": "15.6-inch FHD+ InfinityEdge display, 13th Gen Intel Core i7, 16GB DDR5 RAM, 512GB SSD for creative professionals.",
        "image_url": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-002",
        "featured": 1,
    },
    {
        "name": "Sony WH-1000XM5 Wireless Headphones",
        "category": "Electronics",
        "brand": "Sony",
        "price": 33398,
        "original_price": 38387,
        "discount_percentage": 13,
        "stock": 25,
        "rating": 4.8,
        "review_count": 520,
        "description": "Industry-leading noise canceling headphones with Auto NC Optimizer, crystal clear hands-free calling, and 30-hour battery life.",
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-003",
        "featured": 1,
    },
    {
        "name": "Samsung Galaxy S24 Ultra",
        "category": "Electronics",
        "brand": "Samsung",
        "price": 115163,
        "original_price": 124760,
        "discount_percentage": 8,
        "stock": 18,
        "rating": 4.9,
        "review_count": 310,
        "description": "Galaxy AI integrated, 200MP camera with Optical Zoom, S Pen support, Titanium frame, and Snapdragon 8 Gen 3 chipset.",
        "image_url": "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-004",
        "featured": 1,
    },
    {
        "name": "Apple Watch Series 9 GPS",
        "category": "Electronics",
        "brand": "Apple",
        "price": 38292,
        "original_price": 41171,
        "discount_percentage": 7,
        "stock": 20,
        "rating": 4.7,
        "review_count": 180,
        "description": "S9 SiP chip, double tap gesture control, brighter display, faster on-device Siri, and advanced health tracking features.",
        "image_url": "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-005",
        "featured": 0,
    },
    {
        "name": "Logitech MX Master 3S Wireless Mouse",
        "category": "Electronics",
        "brand": "Logitech",
        "price": 9596,
        "original_price": 10556,
        "discount_percentage": 9,
        "stock": 40,
        "rating": 4.8,
        "review_count": 450,
        "description": "Ergonomic performance mouse with quiet clicks, 8K DPI any-surface tracking, and MagSpeed electromagnetic scrolling wheel.",
        "image_url": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-006",
        "featured": 0,
    },
    {
        "name": "Logitech G Pro X Mechanical Keyboard",
        "category": "Electronics",
        "brand": "Logitech",
        "price": 12475,
        "original_price": 14395,
        "discount_percentage": 13,
        "stock": 30,
        "rating": 4.6,
        "review_count": 210,
        "description": "Pro-grade mechanical gaming keyboard featuring user-swappable mechanical switches and LIGHTSYNC RGB lighting.",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-007",
        "featured": 0,
    },
    {
        "name": "JBL Flip 6 Portable Bluetooth Speaker",
        "category": "Electronics",
        "brand": "JBL",
        "price": 11512,
        "original_price": 12471,
        "discount_percentage": 8,
        "stock": 35,
        "rating": 4.7,
        "review_count": 340,
        "description": "IP67 waterproof and dustproof portable Bluetooth speaker with bold sound and up to 12 hours of playtime.",
        "image_url": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-008",
        "featured": 0,
    },
    {
        "name": "Samsung 55-Inch QLED 4K Smart TV",
        "category": "Electronics",
        "brand": "Samsung",
        "price": 66986,
        "original_price": 76775,
        "discount_percentage": 13,
        "stock": 8,
        "rating": 4.8,
        "review_count": 165,
        "description": "Quantum Processor 4K, 100% Color Volume with Quantum Dot, Motion Xcelerator Turbo+, and Smart TV powered by Tizen.",
        "image_url": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-009",
        "featured": 1,
    },
    {
        "name": "Canon EOS R6 Mark II Mirrorless Camera",
        "category": "Electronics",
        "brand": "Canon",
        "price": 220635,
        "original_price": 239829,
        "discount_percentage": 8,
        "stock": 5,
        "rating": 4.9,
        "review_count": 88,
        "description": "24.2 MP full-frame CMOS sensor, 4K60p video recording, Dual Pixel CMOS AF II, and in-body image stabilization.",
        "image_url": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-010",
        "featured": 0,
    },
    {
        "name": "Anker 737 Power Bank (PowerCore 24K)",
        "category": "Electronics",
        "brand": "Anker",
        "price": 1056.0,
        "original_price": 1495.0,
        "discount_percentage": 27,
        "stock": 50,
        "rating": 4.8,
        "review_count": 620,
        "description": "Ultra-powerful 24,000mAh battery capacity with 140W two-way fast charging and smart digital display.",
        "image_url": "https://images.unsplash.com/photo-1609592424009-5400d36ca47a?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-011",
        "featured": 0,
    },
    {
        "name": "Asus ROG Swift 27-inch 144Hz Gaming Monitor",
        "category": "Electronics",
        "brand": "Asus",
        "price": 31669,
        "original_price": 36468,
        "discount_percentage": 13,
        "stock": 14,
        "rating": 4.7,
        "review_count": 140,
        "description": "27-inch WQHD (2560 x 1440) IPS gaming monitor with 144Hz refresh rate, 1ms response time, and G-SYNC compatible.",
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-ELE-012",
        "featured": 0,
    },
    {
        "name": "Men's Classic Slim Fit Oxford Shirt",
        "category": "Fashion",
        "brand": "Levi's",
        "price": 439.0,
        "original_price": 578.0,
        "discount_percentage": 25,
        "stock": 45,
        "rating": 4.5,
        "review_count": 190,
        "description": "Premium 100% breathable cotton slim fit shirt with button-down collar, perfect for smart casual look.",
        "image_url": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-001",
        "featured": 1,
    },
    {
        "name": "Women's Floral Summer Maxi Dress",
        "category": "Fashion",
        "brand": "Zara",
        "price": 577.0,
        "original_price": 767.0,
        "discount_percentage": 25,
        "stock": 30,
        "rating": 4.6,
        "review_count": 145,
        "description": "Lightweight chiffon floral print maxi dress featuring adjustable waist sash and feminine V-neckline.",
        "image_url": "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-002",
        "featured": 1,
    },
    {
        "name": "Nike Air Max 270 Sneakers",
        "category": "Fashion",
        "brand": "Nike",
        "price": 14395,
        "original_price": 15355,
        "discount_percentage": 6,
        "stock": 22,
        "rating": 4.8,
        "review_count": 480,
        "description": "Nike's first lifestyle Air Max unit delivers style, comfort, and big attitude in every step.",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-003",
        "featured": 1,
    },
    {
        "name": "Adidas Ultraboost Light Running Shoes",
        "category": "Fashion",
        "brand": "Adidas",
        "price": 13435,
        "original_price": 17275,
        "discount_percentage": 22,
        "stock": 28,
        "rating": 4.7,
        "review_count": 290,
        "description": "Lightest Ultraboost ever made with Light BOOST material for maximum energy return and step cushion.",
        "image_url": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-004",
        "featured": 0,
    },
    {
        "name": "Levi's 501 Original Fit Jeans",
        "category": "Fashion",
        "brand": "Levi's",
        "price": 6670,
        "original_price": 7630,
        "discount_percentage": 13,
        "stock": 50,
        "rating": 4.6,
        "review_count": 380,
        "description": "The original straight fit jean since 1873. Crafted in durable non-stretch denim with signature button fly.",
        "image_url": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-005",
        "featured": 0,
    },
    {
        "name": "Fossil Minimalist Leather Quartz Watch",
        "category": "Fashion",
        "brand": "Fossil",
        "price": 851.0,
        "original_price": 1156.0,
        "discount_percentage": 26,
        "stock": 18,
        "rating": 4.5,
        "review_count": 130,
        "description": "Sleek 44mm stainless steel case with genuine brown leather strap and scratch-resistant mineral crystal glass.",
        "image_url": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-006",
        "featured": 0,
    },
    {
        "name": "Ray-Ban Classic Wayfarer Sunglasses",
        "category": "Fashion",
        "brand": "Ray-Ban",
        "price": 15643,
        "original_price": 17275,
        "discount_percentage": 9,
        "stock": 20,
        "rating": 4.8,
        "review_count": 210,
        "description": "Timeless iconic frame with 100% UV protection G-15 glass lenses and acetate black frame.",
        "image_url": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-007",
        "featured": 0,
    },
    {
        "name": "Herschel Little America Laptop Backpack",
        "category": "Fashion",
        "brand": "Herschel",
        "price": 8636,
        "original_price": 10556,
        "discount_percentage": 18,
        "stock": 35,
        "rating": 4.7,
        "review_count": 310,
        "description": "Mountaineering style 25L travel backpack with fleece-lined 15-inch laptop sleeve and drawcord closure.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-008",
        "featured": 0,
    },
    {
        "name": "Tommy Hilfiger Men's Leather Bi-Fold Wallet",
        "category": "Fashion",
        "brand": "Tommy Hilfiger",
        "price": 2735,
        "original_price": 3647,
        "discount_percentage": 25,
        "stock": 60,
        "rating": 4.6,
        "review_count": 420,
        "description": "100% genuine cowhide leather wallet featuring RFID blocking protection, 6 card slots, and bill compartment.",
        "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-009",
        "featured": 0,
    },
    {
        "name": "Kids' Waterproof Hooded Winter Jacket",
        "category": "Fashion",
        "brand": "Columbia",
        "price": 527.0,
        "original_price": 7198.0,
        "discount_percentage": 27,
        "stock": 25,
        "rating": 4.6,
        "review_count": 85,
        "description": "Insulated fleece-lined storm jacket designed to keep kids warm and dry during cold weather outdoor activities.",
        "image_url": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-FAS-010",
        "featured": 0,
    },
    {
        "name": "Ninja Air Fryer XL 5.5 Qt",
        "category": "Home & Kitchen",
        "brand": "Ninja",
        "price": 11515,
        "original_price": 15354,
        "discount_percentage": 25,
        "stock": 20,
        "rating": 4.8,
        "review_count": 610,
        "description": "5.5-quart nonstick ceramic basket air fryer with air fry, air roast, reheat, and dehydrate functionality.",
        "image_url": "https://images.unsplash.com/photo-1585515320310-259814833e62?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-HOM-001",
        "featured": 1,
    },
    {
        "name": "Nespresso VertuoPlus Coffee & Espresso Machine",
        "category": "Home & Kitchen",
        "brand": "Nespresso",
        "price": 14300,
        "original_price": 19098,
        "discount_percentage": 25,
        "stock": 16,
        "rating": 4.7,
        "review_count": 390,
        "description": "Single-serve coffee brewer using Centrifusion technology for rich crema espresso and barista quality coffee.",
        "image_url": "https://images.unsplash.com/photo-1517668808822-9fea0282b941?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-HOM-002",
        "featured": 1,
    },
    {
        "name": "Cuisinart 12-Piece Stainless Steel Cookware Set",
        "category": "Home & Kitchen",
        "brand": "Cuisinart",
        "price": 2112.0,
        "original_price": 2870.0,
        "discount_percentage": 27,
        "stock": 12,
        "rating": 4.6,
        "review_count": 175,
        "description": "Professional triple-ply construction features an aluminum core bonded to stainless steel for optimal heat distribution.",
        "image_url": "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-HOM-003",
        "featured": 0,
    },
    {
        "name": "iRobot Roomba 694 Robot Vacuum",
        "category": "Home & Kitchen",
        "brand": "iRobot",
        "price": 1913.0,
        "original_price": 2631.0,
        "discount_percentage": 27,
        "stock": 15,
        "rating": 4.5,
        "review_count": 520,
        "description": "Wi-Fi connected robot vacuum with 3-stage cleaning system, dual multi-surface brushes, and adaptive sensors.",
        "image_url": "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-HOM-004",
        "featured": 0,
    },
    {
        "name": "Dyson V11 Cordless Stick Vacuum Cleaner",
        "category": "Home & Kitchen",
        "brand": "Dyson",
        "price": 47984,
        "original_price": 57581,
        "discount_percentage": 17,
        "stock": 9,
        "rating": 4.8,
        "review_count": 280,
        "description": "Intelligent cordless vacuum with dynamic load sensor technology and LCD screen reporting battery runtime.",
        "image_url": "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-HOM-005",
        "featured": 0,
    },
    {
        "name": "Modern LED Touch Desk Lamp",
        "category": "Home & Kitchen",
        "brand": "Philips",
        "price": 3358,
        "original_price": 4318,
        "discount_percentage": 22,
        "stock": 40,
        "rating": 4.6,
        "review_count": 190,
        "description": "Dimmable eye-caring LED desk lamp with USB charging port, 5 color modes, and 10 brightness levels.",
        "image_url": "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-HOM-006",
        "featured": 0,
    },
    {
        "name": "Ergonomic Velvet Accent Sofa Armchair",
        "category": "Home & Kitchen",
        "brand": "IKEA",
        "price": 23897,
        "original_price": 28695,
        "discount_percentage": 17,
        "stock": 7,
        "rating": 4.7,
        "review_count": 95,
        "description": "Mid-century modern accent chair upholstered in soft stain-resistant velvet fabric with gold metal legs.",
        "image_url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-HOM-007",
        "featured": 0,
    },
    {
        "name": "Vitamix Explorian Professional Blender",
        "category": "Home & Kitchen",
        "brand": "Vitamix",
        "price": 28786,
        "original_price": 33585,
        "discount_percentage": 14,
        "stock": 11,
        "rating": 4.9,
        "review_count": 310,
        "description": "Variable speed control and pulse feature allow you to refine every texture from smooth purées to chunky soups.",
        "image_url": "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-HOM-008",
        "featured": 0,
    },
    {
        "name": "CeraVe Hydrating Facial Cleanser 16oz",
        "category": "Beauty & Personal Care",
        "brand": "CeraVe",
        "price": 1487,
        "original_price": 1822,
        "discount_percentage": 18,
        "stock": 75,
        "rating": 4.8,
        "review_count": 890,
        "description": "Non-foaming face wash formulated with hyaluronic acid and 3 essential ceramides for normal to dry skin.",
        "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BEA-001",
        "featured": 1,
    },
    {
        "name": "Dyson Supersonic Hair Dryer",
        "category": "Beauty & Personal Care",
        "brand": "Dyson",
        "price": 41266,
        "original_price": 44145,
        "discount_percentage": 7,
        "stock": 14,
        "rating": 4.8,
        "review_count": 340,
        "description": "Fast drying with no extreme heat. Engineed for different hair types with magnetic styling attachments.",
        "image_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BEA-002",
        "featured": 0,
    },
    {
        "name": "Bleu de Chanel Eau de Parfum 100ml",
        "category": "Beauty & Personal Care",
        "brand": "Chanel",
        "price": 14875,
        "original_price": 16315,
        "discount_percentage": 9,
        "stock": 18,
        "rating": 4.9,
        "review_count": 280,
        "description": "An aromatic, deeply woody fragrance with fresh citrus notes and ambery cedar for a bold, elegant trail.",
        "image_url": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BEA-003",
        "featured": 0,
    },
    {
        "name": "Philips Norelco Series 9000 Electric Shaver",
        "category": "Beauty & Personal Care",
        "brand": "Philips",
        "price": 19193,
        "original_price": 23992,
        "discount_percentage": 20,
        "stock": 22,
        "rating": 4.7,
        "review_count": 195,
        "description": "SmartClick precision trimmer, Dual SteelPrecision blades, and SenseIQ skin comfort sensor.",
        "image_url": "https://images.unsplash.com/photo-1621607512214-68297480165e?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BEA-004",
        "featured": 0,
    },
    {
        "name": "The Ordinary Niacinamide 10% + Zinc 1%",
        "category": "Beauty & Personal Care",
        "brand": "The Ordinary",
        "price": 624,
        "original_price": 768,
        "discount_percentage": 19,
        "stock": 100,
        "rating": 4.6,
        "review_count": 1200,
        "description": "High-strength vitamin and mineral blemish formula designed to reduce visible skin blemishes and congestion.",
        "image_url": "https://images.unsplash.com/photo-1608248597261-833258657b39?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BEA-005",
        "featured": 0,
    },
    {
        "name": "Olaplex No. 3 Hair Perfector Repairing Treatment",
        "category": "Beauty & Personal Care",
        "brand": "Olaplex",
        "price": 2879,
        "original_price": 3359,
        "discount_percentage": 14,
        "stock": 45,
        "rating": 4.7,
        "review_count": 780,
        "description": "At-home bond building treatment that reduces breakage and visibly strengthens hair, improving its look and feel.",
        "image_url": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BEA-006",
        "featured": 0,
    },
    {
        "name": "Organic Japanese Matcha Green Tea Powder 100g",
        "category": "Grocery",
        "brand": "Matchaful",
        "price": 2398,
        "original_price": 2878,
        "discount_percentage": 17,
        "stock": 50,
        "rating": 4.8,
        "review_count": 210,
        "description": "Ceremonial grade 100% organic shade-grown matcha powder from Uji, Japan. Rich in L-theanine and antioxidants.",
        "image_url": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-GRO-001",
        "featured": 0,
    },
    {
        "name": "California Whole Raw Almonds 2 lbs",
        "category": "Grocery",
        "brand": "Kirkland",
        "price": 1343,
        "original_price": 1631,
        "discount_percentage": 18,
        "stock": 80,
        "rating": 4.7,
        "review_count": 430,
        "description": "Unsalted, unroasted, non-GMO whole raw almonds packed with healthy fats, fiber, protein, and magnesium.",
        "image_url": "https://images.unsplash.com/photo-1508061252966-177242194c6f?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-GRO-002",
        "featured": 0,
    },
    {
        "name": "Italian Cold Pressed Extra Virgin Olive Oil 1L",
        "category": "Grocery",
        "brand": "Filippo Berio",
        "price": 1775,
        "original_price": 2111,
        "discount_percentage": 16,
        "stock": 40,
        "rating": 4.9,
        "review_count": 310,
        "description": "First cold pressed 100% Mediterranean extra virgin olive oil with rich fruity aroma and peppery finish.",
        "image_url": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-GRO-003",
        "featured": 0,
    },
    {
        "name": "Lindt Excellence 85% Cocoa Dark Chocolate Bar",
        "category": "Grocery",
        "brand": "Lindt",
        "price": 412,
        "original_price": 527,
        "discount_percentage": 22,
        "stock": 120,
        "rating": 4.8,
        "review_count": 650,
        "description": "Master Swiss dark chocolate bar delivering robust roasted cocoa flavor and subtle vanilla undertones.",
        "image_url": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-GRO-004",
        "featured": 0,
    },
    {
        "name": "Organic Whole Grain Rolled Oats 3 lbs",
        "category": "Grocery",
        "brand": "Bob's Red Mill",
        "price": 959,
        "original_price": 1199,
        "discount_percentage": 20,
        "stock": 60,
        "rating": 4.7,
        "review_count": 280,
        "description": "Kiln roasted 100% whole grain oat groats for hearty porridge, granola, and baked healthy breakfast treats.",
        "image_url": "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-GRO-005",
        "featured": 0,
    },
    {
        "name": "Artisanal Single-Origin Arabica Coffee Beans 1 lb",
        "category": "Grocery",
        "brand": "Blue Bottle",
        "price": 1918,
        "original_price": 2303,
        "discount_percentage": 17,
        "stock": 35,
        "rating": 4.9,
        "review_count": 190,
        "description": "Freshly medium-roasted Ethiopian single-origin specialty Arabica beans featuring notes of blueberry and jasmine.",
        "image_url": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-GRO-006",
        "featured": 1,
    },
    {
        "name": "Manduka PRO Yoga Mat 6mm",
        "category": "Sports & Fitness",
        "brand": "Manduka",
        "price": 12284,
        "original_price": 13244,
        "discount_percentage": 7,
        "stock": 25,
        "rating": 4.9,
        "review_count": 320,
        "description": "Ultra-dense non-slip cushioning yoga mat with lifetime guarantee, perfect for hot yoga and intense workouts.",
        "image_url": "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-SPO-001",
        "featured": 1,
    },
    {
        "name": "Bowflex SelectTech 552 Adjustable Dumbbells",
        "category": "Sports & Fitness",
        "brand": "Bowflex",
        "price": 36373,
        "original_price": 41171,
        "discount_percentage": 12,
        "stock": 10,
        "rating": 4.8,
        "review_count": 540,
        "description": "Adjustable from 5 to 52.5 lbs per dumbbell in 2.5 lb increments with quiet molding dial system.",
        "image_url": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-SPO-002",
        "featured": 1,
    },
    {
        "name": "Garmin Forerunner 265 Running Smartwatch",
        "category": "Sports & Fitness",
        "brand": "Garmin",
        "price": 43186,
        "original_price": 47984,
        "discount_percentage": 10,
        "stock": 15,
        "rating": 4.8,
        "review_count": 210,
        "description": "Bright AMOLED touchscreen display, multi-band GPS tracking, training readiness score, and morning report.",
        "image_url": "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-SPO-003",
        "featured": 0,
    },
    {
        "name": "Hydro Flask 32 oz Wide Mouth Water Bottle",
        "category": "Sports & Fitness",
        "brand": "Hydro Flask",
        "price": 3834,
        "original_price": 4314,
        "discount_percentage": 11,
        "stock": 50,
        "rating": 4.9,
        "review_count": 890,
        "description": "TempShield double-wall vacuum insulation keeps beverages cold up to 24 hours and hot up to 12 hours.",
        "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-SPO-004",
        "featured": 0,
    },
    {
        "name": "Wilson Evolution Official Game Basketball",
        "category": "Sports & Fitness",
        "brand": "Wilson",
        "price": 6233,
        "original_price": 7673,
        "discount_percentage": 19,
        "stock": 30,
        "rating": 4.9,
        "review_count": 460,
        "description": "Microfiber composite cover with laid-in channels providing exceptional grip and control for indoor play.",
        "image_url": "https://images.unsplash.com/photo-1519861531473-9200262188bf?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-SPO-005",
        "featured": 0,
    },
    {
        "name": "TRX All-in-One Suspension Trainer Harness",
        "category": "Sports & Fitness",
        "brand": "TRX",
        "price": 16310,
        "original_price": 19189,
        "discount_percentage": 15,
        "stock": 18,
        "rating": 4.7,
        "review_count": 175,
        "description": "Full body bodyweight workout system with indoor/outdoor anchors and mesh carry bag.",
        "image_url": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-SPO-006",
        "featured": 0,
    },
    {
        "name": "Atomic Habits by James Clear (Hardcover)",
        "category": "Books & Education",
        "brand": "Penguin Press",
        "price": 161.0,
        "original_price": 251.0,
        "discount_percentage": 37,
        "stock": 60,
        "rating": 4.9,
        "review_count": 1500,
        "description": "An easy & proven way to build good habits & break bad ones. Millions of copies sold worldwide.",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BOO-001",
        "featured": 1,
    },
    {
        "name": "Designing Data-Intensive Applications",
        "category": "Books & Education",
        "brand": "O'Reilly Media",
        "price": 3695,
        "original_price": 4798,
        "discount_percentage": 23,
        "stock": 35,
        "rating": 4.9,
        "review_count": 420,
        "description": "The definitive guide to architecture, scalability, consistency, and reliability in distributed systems by Martin Kleppmann.",
        "image_url": "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BOO-002",
        "featured": 0,
    },
    {
        "name": "Moleskine Classic Hardcover Notebook Large",
        "category": "Books & Education",
        "brand": "Moleskine",
        "price": 2111,
        "original_price": 2490,
        "discount_percentage": 15,
        "stock": 50,
        "rating": 4.7,
        "review_count": 680,
        "description": "Durable thread-bound notebook with ivory acid-free 70gsm pages, elastic closure, and bookmark ribbon.",
        "image_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BOO-003",
        "featured": 0,
    },
    {
        "name": "PILOT G2 Premium Gel Pens 12-Pack Black",
        "category": "Books & Education",
        "brand": "Pilot",
        "price": 1371,
        "original_price": 1822,
        "discount_percentage": 25,
        "stock": 90,
        "rating": 4.8,
        "review_count": 1100,
        "description": "Longest writing gel ink pen with comfortable contoured rubber grip and fine 0.7mm point.",
        "image_url": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BOO-004",
        "featured": 0,
    },
    {
        "name": "Kindle Paperwhite 16GB E-Reader 6.8\" Display",
        "category": "Books & Education",
        "brand": "Amazon",
        "price": 13435,
        "original_price": 14395,
        "discount_percentage": 7,
        "stock": 25,
        "rating": 4.8,
        "review_count": 790,
        "description": "Glare-free 300 ppi display, adjustable warm light, waterproof design, and battery life up to 10 weeks.",
        "image_url": "https://images.unsplash.com/photo-1592496001020-d31bd830651f?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-BOO-005",
        "featured": 0,
    },
    {
        "name": "LEGO Star Wars Millennium Falcon 75257",
        "category": "Toys & Games",
        "brand": "LEGO",
        "price": 13051,
        "original_price": 16314,
        "discount_percentage": 20,
        "stock": 14,
        "rating": 4.9,
        "review_count": 310,
        "description": "Iconic 1,351-piece Starship model featuring rotating gun turrets, spring-loaded shooters, and 7 minifigures.",
        "image_url": "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-TOY-001",
        "featured": 1,
    },
    {
        "name": "Catan Board Game (Base Game)",
        "category": "Toys & Games",
        "brand": "Catan",
        "price": 4223,
        "original_price": 5278,
        "discount_percentage": 20,
        "stock": 30,
        "rating": 4.8,
        "review_count": 920,
        "description": "Picture yourself in the era of discovery: harvest resource tiles, trade with players, and settle the island of Catan.",
        "image_url": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-TOY-002",
        "featured": 0,
    },
    {
        "name": "Handcrafted Wooden Tournament Chess Set",
        "category": "Toys & Games",
        "brand": "Staunton",
        "price": 6717,
        "original_price": 8636,
        "discount_percentage": 22,
        "stock": 20,
        "rating": 4.7,
        "review_count": 180,
        "description": "15-inch folding magnetic wooden board with weighted carved Staunton wood pieces and velvet storage slots.",
        "image_url": "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-TOY-003",
        "featured": 0,
    },
    {
        "name": "High-Speed 4WD Remote Control Off-Road Truck",
        "category": "Toys & Games",
        "brand": "Bezgar",
        "price": 7677,
        "original_price": 9596,
        "discount_percentage": 20,
        "stock": 22,
        "rating": 4.6,
        "review_count": 240,
        "description": "1:16 scale 40 km/h all-terrain electric monster RC truck with dual rechargeable batteries.",
        "image_url": "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-TOY-004",
        "featured": 0,
    },
    {
        "name": "Ravensburger 1000 Piece Jigsaw Puzzle - World Map",
        "category": "Toys & Games",
        "brand": "Ravensburger",
        "price": 1918,
        "original_price": 2398,
        "discount_percentage": 20,
        "stock": 40,
        "rating": 4.8,
        "review_count": 310,
        "description": "Softclick technology precise fit puzzle pieces with glare-free linen paper finish.",
        "image_url": "https://images.unsplash.com/photo-1563941433-b6a0946f79d8?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-TOY-005",
        "featured": 0,
    },
    {
        "name": "Vantrue N2 Pro Dual 1080P Dash Cam",
        "category": "Automotive",
        "brand": "Vantrue",
        "price": 15354,
        "original_price": 19193,
        "discount_percentage": 20,
        "stock": 15,
        "rating": 4.7,
        "review_count": 380,
        "description": "Dual lens dash cam recording front road and interior cabin simultaneously with infrared night vision.",
        "image_url": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-AUT-001",
        "featured": 0,
    },
    {
        "name": "Chemical Guys All-in-One Car Wash Kit",
        "category": "Automotive",
        "brand": "Chemical Guys",
        "price": 8636,
        "original_price": 10557,
        "discount_percentage": 18,
        "stock": 25,
        "rating": 4.8,
        "review_count": 510,
        "description": "16-piece complete detailing car care bucket kit including Citrus Wash & Gloss, wheel cleaner, and microfiber towels.",
        "image_url": "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-AUT-002",
        "featured": 1,
    },
    {
        "name": "NOCO Boost Plus GB40 1000A Jump Starter",
        "category": "Automotive",
        "brand": "NOCO",
        "price": 9592,
        "original_price": 11991,
        "discount_percentage": 20,
        "stock": 30,
        "rating": 4.9,
        "review_count": 1400,
        "description": "Compact 12V lithium car battery jump starter box for up to 6-liter gasoline and 3-liter diesel engines.",
        "image_url": "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-AUT-003",
        "featured": 0,
    },
    {
        "name": "Quad Lock Motorcycle Vibration Dampener Mount",
        "category": "Automotive",
        "brand": "Quad Lock",
        "price": 4794,
        "original_price": 5753,
        "discount_percentage": 17,
        "stock": 35,
        "rating": 4.8,
        "review_count": 270,
        "description": "Patented dual-stage lock mount designed to reduce over 90% of high-frequency vibrations from bike engines.",
        "image_url": "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-AUT-004",
        "featured": 0,
    },
    {
        "name": "Blue Buffalo Life Protection Adult Dry Dog Food 30 lb",
        "category": "Pet Supplies",
        "brand": "Blue Buffalo",
        "price": 6236,
        "original_price": 7197,
        "discount_percentage": 13,
        "stock": 40,
        "rating": 4.8,
        "review_count": 890,
        "description": "Formulated with deboned real chicken, wholesome whole grains, garden veggies, and antioxidant LifeSource Bits.",
        "image_url": "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-PET-001",
        "featured": 1,
    },
    {
        "name": "Catit Flower Fountain 3L Automatic Pet Water Dispenser",
        "category": "Pet Supplies",
        "brand": "Catit",
        "price": 2878,
        "original_price": 3358,
        "discount_percentage": 14,
        "stock": 30,
        "rating": 4.6,
        "review_count": 420,
        "description": "Triple-action filter recirculates water with 3 water flow settings to entice cats to drink more water.",
        "image_url": "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-PET-002",
        "featured": 0,
    },
    {
        "name": "FURminator Undercoat Deshedding Tool for Dogs",
        "category": "Pet Supplies",
        "brand": "FURminator",
        "price": 3023,
        "original_price": 3838,
        "discount_percentage": 21,
        "stock": 45,
        "rating": 4.7,
        "review_count": 630,
        "description": "Stainless steel deshedding edge reaches through topcoat to safely remove loose hair without damaging topcoat.",
        "image_url": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-PET-003",
        "featured": 0,
    },
    {
        "name": "Padded No-Pull Dog Harness with Leash",
        "category": "Pet Supplies",
        "brand": "Rabbitgoo",
        "price": 2110,
        "original_price": 2686,
        "discount_percentage": 21,
        "stock": 50,
        "rating": 4.7,
        "review_count": 750,
        "description": "Breathable mesh vest harness with dual metal leash rings, easy reflective strips, and top grab handle.",
        "image_url": "https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-PET-004",
        "featured": 0,
    },
    {
        "name": "Cabeau Evolution S3 Ergonomic Travel Memory Foam Pillow",
        "category": "Other",
        "brand": "Cabeau",
        "price": 3838,
        "original_price": 4798,
        "discount_percentage": 20,
        "stock": 30,
        "rating": 4.7,
        "review_count": 230,
        "description": "Patented seat strap system attaches to airplane headrests to prevent head falling forward during flights.",
        "image_url": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-OTH-001",
        "featured": 0,
    },
    {
        "name": "Repel Windproof Double Vent Travel Umbrella",
        "category": "Other",
        "brand": "Repel",
        "price": 2203,
        "original_price": 2874,
        "discount_percentage": 23,
        "stock": 60,
        "rating": 4.6,
        "review_count": 510,
        "description": "Automatic open/close compact umbrella with 9 resin-reinforced fiberglass ribs and Teflon waterproof canopy.",
        "image_url": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-OTH-002",
        "featured": 0,
    },
    {
        "name": "Leatherman Wave Plus 18-in-1 Multi-Tool",
        "category": "Other",
        "brand": "Leatherman",
        "price": 11512,
        "original_price": 13431,
        "discount_percentage": 14,
        "stock": 25,
        "rating": 4.9,
        "review_count": 820,
        "description": "Stainless steel multi-tool equipped with replaceable wire cutters, outside-accessible blades, and locking tools.",
        "image_url": "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=500&auto=format&fit=crop&q=60",
        "sku": "MK-OTH-003",
        "featured": 1,
    },
]
